# $HOME/.k9s/plugin.yml
# move selected line to chosen resource in K9s, then:
# Shift-T (with confirmation) to toggle helm releases or kustomizations suspend and resume
# Shift-R (no confirmation) to reconcile a git source or a helm release or a kustomization
plugin:
  toggle-helmrelease:
    shortCut: Shift-T
    confirm: true
    scopes:
      - helmreleases
    description: Toggle to suspend or resume a HelmRelease
    command: bash
    background: true
    args:
      - -c
      - "/Users/fdesjeunes/scripts/res-suspended.sh $CONTEXT $NAMESPACE hr $NAME 2>&1 | less"
  toggle-kustomization:
    shortCut: Shift-T
    confirm: true
    scopes:
      - kustomizations
    description: Toggle to suspend or resume a Kustomization
    command: bash
    background: true
    args:
      - -c
      - "/Users/fdesjeunes/scripts/res-suspended.sh $CONTEXT $NAMESPACE ks $NAME"
  reconcile-git:
    shortCut: Shift-R
    confirm: false
    description: Flux reconcile
    scopes:
    - gitrepositories
    command: bash
    background: false
    args:
    - -c
    - "flux --context $CONTEXT reconcile source git -n $NAMESPACE $NAME 2>&1 | less"
  reconcile-hr:
    shortCut: Shift-R
    confirm: false
    description: Flux reconcile
    scopes:
    - helmreleases
    command: bash
    background: true
    args:
    - -c
    - "flux --context $CONTEXT reconcile helmrelease -n $NAMESPACE $NAME 2>&1 | less"
  reconcile-ks:
    shortCut: Shift-R
    confirm: false
    description: Flux reconcile
    scopes:
    - kustomizations
    command: bash
    background: true
    args:
    - -c
    - "flux --context $CONTEXT reconcile kustomization -n $NAMESPACE $NAME 2>&1 | less"
  trace:
    shortCut: Shift-A
    confirm: false
    description: Flux trace
    scopes:
    - all
    command: bash
    background: false
    args:
    - -c
    - "flux --context $CONTEXT trace --kind `echo $RESOURCE_NAME | sed -E 's/ies$/y/' | sed -E 's/ses$/se/' | sed -E 's/(s|es)$//g'` --api-version $RESOURCE_GROUP/$RESOURCE_VERSION --namespace $NAMESPACE $NAME 2>&1 | less"

